version: '3.6'

services:
  mcpe-db:
    image: postgres:14-alpine
    container_name: tes-balance-db
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_INITDB_ARGS: "-E UTF8"
